### ISSUE TITLE
Téléchargement conf via github

### ISSUE THREAD

**Issue by lecault** [geo2france/idg-qgis3-plugin#1]
Je viens de remarquer un soucis chez moi je ne sais pas si vous avez le même ou l'avez eu par le passé.

Lorsque je coche télécharger le fichier à chaque lancement ou la case OUI, il me dit que mon fichier de conf n'est pas valide alors que le même copier/coller depuis git en local fonctionne.

![image](https://user-images.githubusercontent.com/5269430/110601191-f8840580-8184-11eb-906d-5a831742f574.png)

Le fichier est ici : https://github.com/geobretagne/qgis-plugin/blob/master/geobretagne/config/config.json

**Comment by Doctor-Who** [comment]
Bonjour @lecault 
Il s'agit du plugin GeoBretagne et non celui de Geo2France, je vous invite à voir directement avec eux.

**Comment by bchartier** [comment]
bah non, @lecault est parfaitement au courant de la situation ; c'est le pilote du fork de GéoBretagne.
Il n'est pas à l'origine de ce code.

**Comment by bchartier** [comment]
@lecault : est-ce que le problème existe toujours ? Est-ce qu'il y a besoin de rouvrir ce ticket ?

**Comment by lecault** [comment]
Le problème vient d'un accès à github. Si je met le fichier ailleurs comme datagrandest, ça passe.
https://geobretagne.fr/pub/qgis-plugin/config.json

On peut clore.

**Comment by bchartier** [comment]
C'est sans doute qu'il faut juste que tu utilises le lien "raw" fourni par Github :
https://raw.githubusercontent.com/geobretagne/qgis-plugin/master/geobretagne/config/config.json

Si tu utilises le lien "normal" de github tu as tout l'habillage HTML, JS mais pas le fichier en lui-même.

**Comment by lecault** [comment]
Je confirme ah c'était trop évident.
Merci Benjamin
