### ISSUE TITLE
Ficher de métadonnées manquant

### ISSUE THREAD

**Issue by vfabry** [geo2france/idg-qgis3-plugin#13]
Bonjour,
Depuis que j'ai mis à jour la liste des couches disponibles (ajout d'un ombrage régional et des couches du GPU - qui ne fonctionnent pas, mais c'est un autre problème - on ne peut plus installer le plugin :

> Cette extension est corrompue. Python dit :
> Ficher de métadonnées manquant

J'ai du faire une fausse manip, mais je ne vois pas où...

Vincent

**Comment by bchartier** [comment]
L'installation fonctionne très bien de mon côté.

Ma config :
- Windows 11
- Dernière version de QGIS LTR
- Utilisation du dépôt en ligne Géo2France depuis le gestionnaire d'extension de QGIS.

Est-ce que tu essaies de l'installer manuellement ou depuis le gestionnaire d'extension ?
On peut voir cela ensemble à partir de demain.

**Comment by bchartier** [comment]
Sinon, on rencontre ce message d'erreur quand QGIS ne trouve pas le fichier `metadata.txt` à la racine du répertoire qui contient le plugin. Cela peut être le cas quand dans le fichier zip on a un répertoire qui contient le répertoire qui contient ce fichier `metadata.txt`.

genre `geo2france/geo2france/metadata.txt`

**Comment by vfabry** [comment]
Je suis revenu à une ancienne version et ça refonctionne. Puis j'ai ajouté la couche d'ombrage régional (github + zip) et ça fonctionne toujours.
Merci Benjamin.
