### ISSUE TITLE
Localisation des paramètres du plugin

### ISSUE THREAD

**Issue by jbdesbas** [geo2france/idg-qgis3-plugin#31]
Actuellement les paramètres du plugin sont gérés dans [plugin_globals.py](https://github.com/geo2france/idg-qgis-plugin/blob/dev/plugin/idg/toolbelt/plugin_globals.py). La classe mélange des constantes et des paramètres.
Le template Oslandia utilise plutôt [preference.py](https://github.com/geo2france/idg-qgis-plugin/blob/dev/plugin/idg/toolbelt/preferences.py) (`PlgOptionsManager`).

Pour écrire une conf : `PlgOptionsManager().set_value_from_key('conf_key','conf_value')`
Pour lire : `PlgOptionsManager.get_plg_settings().conf_key`

Passer l'ensemble des paramètres de `plugin_globals.py` vers `preferences.py`. Mettre les valeurs par défaut ici : https://github.com/geo2france/idg-qgis-plugin/blob/897e40c6a4c0ac963987e66883414ded3ec85220/plugin/idg/toolbelt/preferences.py#L23-L29

Laisser les constantes (`NODE_TYPE_WS` etc.) dans `plugin_globals.py`  ?

**Comment by bchartier** [comment]
> Laisser les constantes (`NODE_TYPE_WS` etc.) dans `plugin_globals.py` ?

Je ne sais pas quel est l'endroit idéal pour cela.
Dans un plugin_globals.py ou avec un autre nom ? Dans __init__.py ?

**Comment by jbdesbas** [comment]
Ca me va pour `plugin_globals.py` !
