### ISSUE TITLE
la couche EPCI ne s'affiche pas

### ISSUE THREAD

**Issue by vfabry** [geo2france/idg-qgis3-plugin#6]
Un utilisateur du plugin remonte ce problème : la couche EPCI disponible dans la section "limites administratives" renvoie le message d'erreur suivant : 
`2021-10-11T10:24:04     CRITICAL    Couche EPCI - BD Topo : Le téléchargement des entités de la couche spld:epci a échoué ou partiellement échoué: Le téléchargement des entités à échoué: Error transferring https://www.geo2france.fr/geoserver/spld/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=spld:epci&TYPENAME=spld:epci&STARTINDEX=0&COUNT=1000000&SRSNAME=urn:ogc:def:crs:EPSG::2154 - server replied: Bad Request. Vous allez sans doute devoir recharger la couche avec F5`
La version du qgis utilisé est 3.4.11
A première vue, j'ai l'impression qu'il y a un problème dans la requête GetFeature, avec un double :: devant le paramètre EPSG
Je n'ai pas cette erreur sur mon QGIS, qui est en version 3.16.3

**Comment by Doctor-Who** [comment]
Je pense que nous pouvons fermer cette issue dans la mesure où cela fonctionne sur la LTR en cours et la dernière 3.22
Pour des raisons d'efficacité et de maintenance, nous ne pouvons supporter des versions antérieures à la LTR.

**Comment by bchartier** [comment]
@vfabry : est-ce que tu peux voir avec l'utilisateur en question si c'est ok pour qu'on ferme cela ?

Si jamais il faut absolument corrigé le truc il faudrait voir si le problème se pose uniquement pour cette couche ou toutes les couches WFS servies par le GeoServer de Géo2France.

Sinon, je suis assez d'accord avec @Doctor-Who pour qu'on ne traite pas les anomalies sur des QGIS plus vieux que la version LTR.
